/* Controller integration in a minimal DOM harness. This is not a browser test. */
const fs=require('node:fs'),vm=require('node:vm'),path=require('node:path'),assert=require('node:assert/strict');
const root=path.resolve(__dirname,'..');const noop=()=>{};let next=1,clock=0;const timers=new Map(),storage=new Map(),els=new Map();
function el(id){if(els.has(id))return els.get(id);const cl=new Set(),listeners={};const e={id,innerHTML:'',textContent:'',disabled:false,checked:false,open:false,tagName:'DIV',dataset:{},width:1000,height:650,style:{},classList:{add:x=>cl.add(x),remove:x=>cl.delete(x),contains:x=>cl.has(x),toggle(x,force){const value=force===undefined?!cl.has(x):force;value?cl.add(x):cl.delete(x);return value}},setAttribute:noop,getBoundingClientRect:()=>({width:1000,height:650,left:0,top:0}),getContext:()=>new Proxy({},{get:()=>noop}),addEventListener:(type,fn)=>listeners[type]=fn,setPointerCapture:noop,showModal(){this.open=true},close(){this.open=false},click:noop,listeners};els.set(id,e);return e}
const html=fs.readFileSync(root+'/src/shell.html','utf8');const ids=[...html.matchAll(/\bid="([^"]+)"/g)].map(x=>x[1]);assert.equal(ids.length,new Set(ids).size);ids.forEach(el);
const doc={getElementById(id){assert(els.has(id),'Missing static element '+id);return el(id)},querySelectorAll:()=>[],addEventListener:noop,createElement:()=>el('download'),hidden:false};
const ctx={document:doc,window:{devicePixelRatio:1,addEventListener:noop,confirm:()=>true},localStorage:{getItem:k=>storage.get(k)||null,setItem:(k,v)=>storage.set(k,v)},console,Image:class{},ART:[],ResizeObserver:class{constructor(fn){this.fn=fn}observe(){this.fn()}},requestAnimationFrame:noop,setTimeout(fn,delay){const id=next++;timers.set(id,{fn,at:clock+delay});return id},clearTimeout:id=>timers.delete(id),Blob,URL,Math,JSON,Set};vm.createContext(ctx);['core','field','render','app'].forEach(n=>vm.runInContext(fs.readFileSync(root+'/src/'+n+'.js','utf8'),ctx,{filename:n+'.js'}));
const UI=vm.runInContext('UI',ctx),Kin=vm.runInContext('Kin',ctx);const read=()=>JSON.parse(storage.get('first-kin-campaign-v6'));
function flush(){let n=0;while(timers.size){assert(n++<500,'Runaway controller timer');const [id,t]=[...timers].sort((a,b)=>a[1].at-b[1].at)[0];timers.delete(id);clock=t.at;t.fn()}}
(async()=>{
 await Promise.resolve();await Promise.resolve();
 const names=[...html.matchAll(/UI\.(\w+)\(/g)].map(x=>x[1]);for(const name of names)assert.equal(typeof UI[name],'function','Missing UI handler '+name);
 UI.begin();assert(read().started);UI.chooseBuild('hut');const p=vm.runInContext('View.project(6,5,View.metrics(1000,650))',ctx);el('worldCanvas').listeners.pointerdown({clientX:p.x,clientY:p.y,pointerId:1});el('worldCanvas').listeners.pointerup({clientX:p.x,clientY:p.y,pointerId:1});assert.equal(read().buildings.at(-1).type,'hut');
 UI.select('strongF');UI.plan(1,'build');UI.fieldToggle(false);UI.run();assert(el('runButton').disabled);flush();assert.equal(read().phase,'dinner');assert(el('dinnerDialog').open);assert.equal(read().buildings.at(-1).done,true);assert.equal(read().people.find(p=>p.id==='youngM').hand.fire,1);
 UI.sleep();assert.equal(read().sun,2);UI.repeat();assert.equal(read().plans.strongF[1],'build');UI.restAll();assert.equal(read().plans.strongF[1],'rest');
 for(const pane of ['people','build','discover','council','memory']){UI.panel(pane);assert(el('sideContent').innerHTML.length>100);for(const h of el('sideContent').innerHTML.matchAll(/UI\.(\w+)\(/g))assert.equal(typeof UI[h[1]],'function')}
 UI.scene('region');assert(!el('regionCard').classList.contains('hidden'));UI.scene('camp');assert(el('regionCard').classList.contains('hidden'));UI.zoom(.2);assert.equal(el('zoomLevel').textContent,'120%');UI.zoom(0);assert.equal(el('zoomLevel').textContent,'100%');
 UI.select('strongM');UI.plan(0,'fish');UI.fieldToggle(true);UI.run();flush();assert(!el('fieldControls').classList.contains('hidden'));assert(el('runButton').disabled);UI.returnEarly();UI.returnHome();flush();assert.equal(read().phase,'dinner');UI.sleep();assert.equal(read().sun,3);
 const old=storage.get('first-kin-campaign-v6');await UI.importSave({size:10,text:async()=>'{"version":6}'});assert.equal(storage.get('first-kin-campaign-v6'),old);UI.load();assert.equal(read().sun,3);assert(Kin.valid(read()));
 console.log('Controller integration passed: start, map placement, AM/PM execution, dinner, sleep, all panels, zoom, field return, save/load and malformed-import rejection.');
})();
