const assert=require('node:assert/strict');global.Kin=require('../src/core.js');global.Field=require('../src/field.js');const {campaign,resolveDay}=require('./campaign.cjs');let count=0;
function check(name,fn){fn();count++;console.log('PASS '+name)}
function blank(){const s=Kin.create();s.people.forEach(p=>s.plans[p.id]=['rest','rest']);return s}
function slot(s){Kin.start(s);Kin.resolveSlot(s)}
function doneBuilding(s,type,x=6,y=7){const b={id:'test_'+type,type,x,y,work:Kin.buildings[type].work,done:true,growth:0,water:0,planted:false};s.buildings.push(b);return b}
function entry(s,scene='hunt',actors=['strongM']){Kin.start(s);s.plans[actors[0]][0]=scene==='party'?'party':scene;if(scene==='party')actors.forEach(id=>s.plans[id][0]='party');Kin.resolveSlot(s);return s.pending[0]}
check('The starting family is a valid save',()=>assert(Kin.valid(blank())));
check('Observation teaches understanding without practical ability',()=>{const s=blank();s.plans.oldM[0]='teach:fire';s.plans.youngM[0]='watch:oldM';slot(s);assert(Kin.get(s,'youngM').know.includes('fire'));assert.equal(Kin.get(s,'youngM').hand.fire,undefined)});
check('Watching then practicing works across the two slots',()=>{const s=blank();s.plans.oldM[0]='teach:fire';s.plans.youngM=['watch:oldM','practice:fire'];resolveDay(s);assert.equal(Kin.get(s,'youngM').hand.fire,1)});
check('A distant provider cannot be watched from camp',()=>{const s=blank();s.plans.strongM[0]='hunt';s.plans.youngM[0]='watch:strongM';slot(s);assert(!Kin.get(s,'youngM').know.includes('hunt'))});
check('Understanding alone does not equip a hunter',()=>{const s=blank();Kin.get(s,'youngM').know.push('hunt');s.plans.youngM[0]='hunt';slot(s);assert.equal(s.pending.length,0)});
check('Spears cannot be used twice in the same slot',()=>{const s=blank();s.tools.spear=1;s.plans.strongM[0]='hunt';s.plans.strongF[0]='hunt';slot(s);assert.equal(s.pending.length,1)});
check('A new tool becomes available in the following slot',()=>{const s=blank();s.tools.spear=0;s.plans.oldM[0]='craft:spear';s.plans.strongM=['hunt','hunt'];slot(s);assert.equal(s.pending.length,0);Kin.resolveSlot(s);assert.equal(s.pending.length,1)});
check('A shared bow is assigned to only one provider',()=>{const s=blank();s.tools.bow=1;s.plans.strongM[0]='hunt';s.plans.strongF[0]='hunt';slot(s);assert.equal(s.pending.reduce((n,e)=>n+e.tools.bow,0),1)});
check('A field result pays out exactly once',()=>{const s=blank(),e=entry(s),r={id:e.id,food:6,hide:1,bone:2,success:true,injuries:{}};const before=s.stock.food;assert(Kin.applyField(s,e,r));assert.equal(s.stock.food,before+6);assert(!Kin.applyField(s,e,r));assert.equal(s.stock.food,before+6)});
check('A catch feeds the provider before contributing to camp',()=>{const s=blank(),e=entry(s,'fish'),n=s.stock.food;Kin.applyField(s,e,{id:e.id,caught:4,food:3,success:true,injuries:{}});assert.equal(s.stock.food,n+3);assert.equal(s.nodes.fish,16)});
check('A field result cannot overdraw a depleted resource',()=>{const s=blank(),e=entry(s,'fish');s.nodes.fish=1;const food=s.stock.food;Kin.applyField(s,e,{id:e.id,caught:100,food:30,success:true});assert.equal(s.nodes.fish,0);assert.equal(s.stock.food,food)});
check('Invalid field numbers are rejected without changing camp',()=>{const s=blank(),e=entry(s);const old=JSON.stringify(s);assert(!Kin.applyField(s,e,{id:e.id,food:6,hide:NaN,success:true}));assert.equal(JSON.stringify(s),old)});
check('Fishing has three timed casts and an actual outcome',()=>{const s=blank(),e=entry(s,'fish'),f=Field.create(s,e);for(let i=0;i<1000&&!f.done;i++){Field.step(f,1/30);if(f.phase==='biting')Field.hook(f)}assert(f.done);assert.equal(f.caught,6);assert.equal(Field.result(f).food,5)});
check('An early pull does not manufacture a fish',()=>{const s=blank(),e=entry(s,'fish'),f=Field.create(s,e);Field.hook(f);assert.equal(f.caught,0);assert.equal(f.phase,'waiting')});
check('Pause stops field time and player attacks',()=>{const s=blank(),e=entry(s),f=Field.create(s,e);f.paused=true;f.actors[0].x=f.prey.x;f.actors[0].y=f.prey.y;Field.step(f,1/30);Field.attack(f);assert.equal(f.time,0);assert.equal(f.prey.hp,5)});
check('The group hunt runs from placed roles to a camp outcome',()=>{const s=blank(),e=entry(s,'party',['strongM','strongF']),f=Field.create(s,e);assert(Field.commit(f));for(let i=0;i<2200&&!f.done;i++)Field.step(f,1/30);assert(f.done);assert(f.success);assert.equal(Field.result(f).food,12);assert(Kin.applyField(s,e,Field.result(f)))});
check('A solo provider can pathfind, pursue and strike',()=>{const s=blank(),e=entry(s),f=Field.create(s,e);for(let i=0;i<2200&&!f.done;i++){if(i%15===0)Field.tap(f,Math.round(f.prey.x),Math.round(f.prey.y));Field.step(f,1/30);Field.attack(f)}assert(f.done);assert(f.success)});
check('Longarm requires a real bow',()=>{const s=blank(),e=entry(s,'party',['strongM','strongF']),f=Field.create(s,e);assert(!Field.setRole(f,0,'longarm'));f.tools.bow=1;assert(Field.setRole(f,0,'longarm'));assert(!Field.setRole(f,1,'longarm'))});
check('An unconnected shelter provides no housing',()=>{const s=blank();assert.equal(Kin.place(s,'hut',8,6),null);const b=s.buildings.at(-1);b.done=true;b.work=2;assert.equal(Kin.capacity(s),6);assert.equal(Kin.place(s,'trail',7,6),null);assert.equal(Kin.capacity(s),9)});
check('Water and occupied ground cannot be built on',()=>{const s=blank(),old=Kin.clone(s.stock);assert(Kin.place(s,'hut',14,5));assert(Kin.place(s,'hut',3,5));assert.deepEqual(s.stock,old)});
check('Building expenses cannot make resources negative',()=>{const s=blank();s.stock.wood=0;const old=Kin.clone(s.stock);assert(Kin.place(s,'hut',6,5));assert.deepEqual(s.stock,old)});
check('Discovery prerequisites gate new construction and tools',()=>{const s=blank();assert(Kin.place(s,'garden',6,5));s.plans.strongF[0]='craft:bow';slot(s);assert.equal(s.tools.bow,0)});
check('A connected storehouse reduces spoilage',()=>{const a=blank(),b=blank();a.stock.greens=b.stock.greens=100;doneBuilding(b,'storage');resolveDay(a);resolveDay(b);assert(a.today.spoiled>b.today.spoiled)});
check('A connected water place supplies the next dawn',()=>{const s=blank();doneBuilding(s,'well');const n=s.stock.water;Kin.start(s);assert.equal(s.stock.water,n+2)});
check('Plots need growing time and water; harvesting returns seeds',()=>{const s=blank(),b=doneBuilding(s,'garden');s.plans.strongF[0]='plant';resolveDay(s);Kin.sleep(s);assert.equal(b.growth,1);for(let d=0;d<3;d++){s.plans.strongF=['tend','rest'];resolveDay(s);Kin.sleep(s)}assert.equal(b.growth,4);s.plans.strongF=['harvest','rest'];const n=s.stock.seed;resolveDay(s);assert.equal(s.stock.seed,n+2);assert(!b.planted)});
check('Winter blocks planting and slows natural food recovery',()=>{const s=blank();s.sun=19;doneBuilding(s,'garden');s.plans.strongF[0]='plant';s.nodes.green=0;resolveDay(s);Kin.sleep(s);assert(!s.buildings.at(-1).planted);assert.equal(s.nodes.green,0)});
check('Malformed imports fail before restoration',()=>{for(const edit of [s=>s.people[0].id="bad' onclick='x",s=>s.people[0].art=99,s=>s.people[0].role=null,s=>s.plans.oldM=['bad','rest'],s=>s.region.outposts=['bogus'],s=>s.stock.food=NaN,s=>s.research.active='__proto__',s=>s.paths=['99,99'],s=>s.people[0].know=['__proto__']]){const s=blank();edit(s);assert(!Kin.valid(s))}});
check('A seeded save resumes with identical outcomes',()=>{const a=blank();a.plans.strongM=['hunt','fish'];const b=JSON.parse(JSON.stringify(a));resolveDay(a);resolveDay(b);assert.deepEqual(a,b)});
check('A normal 30-sun campaign reaches village, trade, crops and an outpost',()=>{const r=campaign(30);assert.equal(r.milestones.tribe,5);assert.equal(r.milestones.village,9);assert.equal(Kin.live(r.s).length,12);assert.equal(r.s.research.done.length,5);assert(r.s.region.outposts.includes('pine'));assert(r.visits>0);assert(r.s.history.some(h=>h.text.includes('harvests')));assert(r.report.every(d=>d.short===0));assert(Kin.valid(r.s))});
console.log(`${count} simulation and progression checks passed.`);
